kind: Service
apiVersion: v1
metadata:
  name: containerapp-weatherapi-svc
spec:
  type: ClusterIP
  selector:
    app: containerapp-weatherapi
    tier: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: containerapp-weatherapi-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: containerapp-weatherapi
      tier: backend
  template:
    metadata:
      labels:
        app: containerapp-weatherapi
        tier: backend
    spec:
      containers:
        - name: containerapp-weatherapi
          image: "_ImageUrlApi_"
          ports:
            - name: http
              containerPort: 80
          resources:
            requests:
              cpu: "250m"
              memory: "64Mi"
            limits:
              cpu: "500m"
              memory: "128Mi"
      imagePullSecrets:
        - name: acr-secret
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: containerapp-weatherapi
  namespace: default
spec:
  path: /
  to:
    kind: Service
    name: containerapp-weatherapi-svc
  port:
    targetPort: 80